-- ============================================================================
-- Instant Mechanic AI - PostgreSQL Database Schema for Neon
-- Compatible with PostgreSQL 15, 16, 17, and Neon Serverless Postgres
-- ============================================================================

-- 1. Conversation Table (Multi-turn chat threads)
CREATE TABLE IF NOT EXISTS "chatbot_conversation" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "session_id" varchar(100) NOT NULL,
    "vehicle_info" varchar(255) NOT NULL DEFAULT '',
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "chatbot_conversation_session_id_idx" 
    ON "chatbot_conversation" ("session_id");

-- 2. Message Table (User, Assistant & Diagnostic messages)
CREATE TABLE IF NOT EXISTS "chatbot_message" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "conversation_id" bigint NOT NULL,
    "role" varchar(20) NOT NULL,
    "content" text NOT NULL,
    "media_type" varchar(20) NULL DEFAULT 'text',
    "media_url" varchar(500) NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "chatbot_message_conv_fk" 
        FOREIGN KEY ("conversation_id") 
        REFERENCES "chatbot_conversation" ("id") 
        ON DELETE CASCADE 
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS "chatbot_message_conversation_id_idx" 
    ON "chatbot_message" ("conversation_id");

-- 3. Diagnosis Table (Structured AI mechanical diagnoses)
CREATE TABLE IF NOT EXISTS "chatbot_diagnosis" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "conversation_id" bigint NOT NULL,
    "symptoms" text NOT NULL,
    "diagnosis" text NOT NULL,
    "severity" varchar(20) NOT NULL DEFAULT 'medium',
    "recommendation" text NOT NULL,
    "service" varchar(255) NOT NULL,
    "reasoning" text NOT NULL DEFAULT '',
    "safety_warning" text NOT NULL DEFAULT '',
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "chatbot_diagnosis_conv_fk" 
        FOREIGN KEY ("conversation_id") 
        REFERENCES "chatbot_conversation" ("id") 
        ON DELETE CASCADE 
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS "chatbot_diagnosis_conversation_id_idx" 
    ON "chatbot_diagnosis" ("conversation_id");

-- 4. Uploaded Media Table (Images, Audio, Video telemetry files)
CREATE TABLE IF NOT EXISTS "chatbot_uploadedmedia" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "file" varchar(100) NOT NULL,
    "media_type" varchar(20) NOT NULL,
    "file_name" varchar(255) NOT NULL DEFAULT '',
    "file_size" integer NOT NULL CHECK ("file_size" >= 0) DEFAULT 0,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Bookings Table (Certified mechanic repair bookings)
CREATE TABLE IF NOT EXISTS "bookings_booking" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "diagnosis_id" bigint NULL,
    "customer_name" varchar(150) NOT NULL,
    "phone" varchar(20) NOT NULL,
    "vehicle" varchar(150) NOT NULL,
    "preferred_date" varchar(30) NOT NULL,
    "preferred_time" varchar(30) NOT NULL,
    "service" varchar(255) NOT NULL,
    "status" varchar(30) NOT NULL DEFAULT 'confirmed',
    "notes" text NOT NULL DEFAULT '',
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "bookings_booking_diagnosis_fk" 
        FOREIGN KEY ("diagnosis_id") 
        REFERENCES "chatbot_diagnosis" ("id") 
        ON DELETE SET NULL 
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS "bookings_booking_diagnosis_id_idx" 
    ON "bookings_booking" ("diagnosis_id");
