# Generated by Django 6.1.1 on 2026-09-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='gemini_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='confidence',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='source',
            field=models.CharField(choices=[('rules', 'Rules Engine'), ('gemini', 'Gemini AI'), ('fallback', 'Fallback Engine')], default='rules', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='vehicle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
