# Generated by Django 6.1.1 on 2026-09-25 10:51

import chatbot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_diagnosticissue_diagnosticquestion_vehiclesystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='operation',
            field=models.CharField(default='interview_planning', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='chatbot.conversation'),
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.CharField(default=chatbot.models.generate_diag_session_id, max_length=64, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_info', models.JSONField(blank=True, default=dict)),
                ('original_message', models.TextField()),
                ('case_context', models.JSONField(blank=True, default=dict)),
                ('interview_plan', models.JSONField(blank=True, default=dict)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('assessment', models.JSONField(blank=True, default=dict)),
                ('gemini_calls', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('collecting_answers', 'Collecting Answers'), ('ready_for_assessment', 'Ready for Assessment'), ('assessing', 'Assessing'), ('completed', 'Completed'), ('failed', 'Failed')], default='planning', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='chatbot.conversation')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='chatbot.diagnosis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('question_text', models.TextField(blank=True, default='')),
                ('answer', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chatbot.diagnosticsession')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='chatbot.diagnosticsession'),
        ),
    ]
